name = "personal-site"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
pages_build_output_dir = ".open-next"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "static-assets"

[vars]
NEXT_INC_CACHE_R2_PREFIX = "incremental-cache"

